"""empty message

Revision ID: 54896640bd4b
Revises: None
Create Date: 2016-01-21 15:19:17.076914

"""

# revision identifiers, used by Alembic.
revision = '54896640bd4b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipient')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipient',
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], [u'message.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('message_id', 'recipient_id')
    )
    ### end Alembic commands ###
